### ISSUE TITLE
Tracking To Do list

### ISSUE THREAD

**Issue by abruck1** [abruck1/APT2017-pink#3]
Login
- [ ] redirect to view all
- [ ] Send the user id/hook up to backend for all intents

View Streams
- [x] - Fix screen size issues
- [x] - dynamically get server streams data
- [x] - Pass stream id to streamView
- [ ] - add load more feature to recyleview
- [x] - Connect Search
- [x] - Go to My subscribed streams
- [ ] - Only show subscribe button if logged in

View A Stream
- [x] - Fix screen size issues
- [x] - dynamically get server streams data

View Nearby Streams
- [ ] -TODO

Search Results
- [x] - Matt is a GENIUS!
- [x] - Display up to 8 images, and get next if available

Upload
- [x] - Fix rectangle
- [x] - Make button visible/invisible
- [x] - Get image from gallery
- [ ] - Do a post on upload
- [x] - Display stream name

Camera
- [x] - Test and see if working

My subscribed Streams
- [x] - TODO Come up with it
- [ ] - Actually delete/unsub from the stream is button pressed

**Comment by jtautry** [comment]
I'm working on upload.
